sudo: false
language: node_js
node_js:
- 10
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_aeeb89b9390d_key -iv $encrypted_aeeb89b9390d_iv -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv deploy_rsa /tmp/deploy_rsa
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- docker build -t mufdvr/citypark_front .
deploy:
  provider: script
  script: bash docker_deploy.sh
  on:
    branch: master
branches:
  only:
  - master
