sudo: false
language: node_js
node_js:
- 10
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_aeeb89b9390d_key -iv $encrypted_aeeb89b9390d_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- openssl aes-256-cbc -K $encrypted_aeeb89b9390d_key -iv $encrypted_aeeb89b9390d_iv -in nginx/ssl/ca_bundled.crt.enc -out nginx/ssl/ca_bundled.crt -d
- openssl aes-256-cbc -K $encrypted_aeeb89b9390d_key -iv $encrypted_aeeb89b9390d_iv -in nginx/ssl/private.key.enc -out nginx/ssl/private.key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- docker build -t mufdvr/citypark_front .
deploy:
  provider: script
  script: bash docker_deploy.sh
  on:
    branch: master
branches:
  only:
  - master
